//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUExamen
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Video
    {
        [ScaffoldColumn(false)]
        public int idVideo { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El título es requerido"), MaxLength(55)]
        [Display(Name = "Título")]
        public string titulo { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [Display(Name = "Fecha de Publicación")]
        public System.DateTime fecha_publicacion { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El formato es requerido"), MaxLength(55)]
        [Display(Name = "Formato")]
        public string formato { get; set; }

        [DataType(DataType.Duration)]
        [Display(Name = "Duración (min)")]
        public int duracion { get; set; }

        [Display(Name = "Categoría")]
        public int idCategoria { get; set; }

        public virtual Categoria Categoria { get; set; }
    }
}
